---
- hosts: all
  gather_facts: yes
  become: true
  tasks:
    - name: Upgrade all packages
      apt:
        upgrade: full
        update_cache: yes
        cache_valid_time: 3600
        autoremove: yes
