---
- name: Install Kali infrastructure metapackages
  apt:
    name:
      - kali-tools-database
      - kali-tools-vulnerability
      - offsec-pwk
    state: present

- name: Install other infrastructure packages
  apt:
    name:
      - finger
      - ldap-utils
      - ridenum
      - rsh-client
      - rwho
      - wmis
    state: present
